-- public.usuarios definition

-- Drop table

-- DROP TABLE public.usuarios;

CREATE TABLE public.usuarios (
	id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	nombres varchar NOT NULL,
	direccion varchar NOT NULL,
	telefono int4 NOT NULL,
	correo varchar NOT NULL,
	CONSTRAINT usuario_pk PRIMARY KEY (id)
);

-- public.vacunas definition

-- Drop table

-- DROP TABLE public.vacunas;

CREATE TABLE public.vacunas (
	id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	nombre varchar NOT NULL,
	CONSTRAINT vacunas_pk PRIMARY KEY (id)
);

-- public.mascotas definition

-- Drop table

-- DROP TABLE public.mascotas;

CREATE TABLE public.mascotas (
	id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	nombres varchar NOT NULL,
	raza varchar NOT NULL,
	edad int4 NOT NULL,
	id_propietario int4 NOT NULL,
	CONSTRAINT mascotas_pk PRIMARY KEY (id)
);


-- public.mascotas foreign keys

ALTER TABLE public.mascotas ADD CONSTRAINT mascotas_fk FOREIGN KEY (id_propietario) REFERENCES public.usuarios(id);

-- public.historial definition

-- Drop table

-- DROP TABLE public.historial;

CREATE TABLE public.historial (
	id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	fecha timestamp NOT NULL,
	id_vacuna int4 NOT NULL,
	id_perro int4 NOT NULL,
	proxima_dosis timestamp NOT NULL,
	CONSTRAINT historial_pk PRIMARY KEY (id)
);


-- public.historial foreign keys

ALTER TABLE public.historial ADD CONSTRAINT historial_fk FOREIGN KEY (id_perro) REFERENCES public.mascotas(id);
ALTER TABLE public.historial ADD CONSTRAINT historial_fk_1 FOREIGN KEY (id_vacuna) REFERENCES public.vacunas(id);
